### ISSUE TITLE
bug: /channelId/schedule 에서 새로고침 시, nav는 초기화 되고, router는 초기화 되지 않아 서로 불일치하는 버그

### ISSUE THREAD

**Issue by starplanter93** [EthanJcoding/LoReady-Web#13]
/channelId/schedule 에서 새로고침 시, nav는 초기화 되고, router는 초기화 되지 않아 서로 불일치하는 버그

원인 : Navigation 컴포넌트의 navTap state의 default value가 'dashboard' 이기 때문에, schedule탭을 클릭하고 새로고침 시, dashboard로 초기화됨. 그러나 router의 경우 새로고침을 하더라도 schedule에 유지되기 때문에 불일치가 발생하는 것으로 추정.

해결 방법 : navigation의 css를 navTap이라는 상태를 통해 관리할 것이아니라, params를 통해 관리해야할 것으로 생각됨.
handleClick 이벤트 핸들러 함수도 단순히 상태를 변경시키는 것이아니라, route를 바꾸는 것으로 동작해야함.

**Comment by kongchip** [comment]
네 확인했습니다 체크하고 수정하겠습니다!
