### ISSUE TITLE
PartyList 컴포넌트 내부 store 분리 요청

### ISSUE THREAD

**Issue by starplanter93** [EthanJcoding/LoReady-Web#16]
![image](https://github.com/EthanJcoding/LoReady-Web/assets/107591946/1260a9c1-dd14-4af0-b55a-7e6cd81c5ce6)

PartyList 내부의 store와 type을 사전에 지정한 디렉토리로 분리시키는 것이 맞는 것 같습니다.

혹시 목데이터로 임시로 만든것일까요? 그렇다면 상관없습니다만...

**Comment by kongchip** [comment]
네 zustand사용해볼겸  목데이터로 사용하려고 파일에 넣어두었습니다. 분리되면 다른분들이 혼동이 생길거같아서 넣어두었는데 주석이나, 다른 커맨트가 없어서 혼동이 생겼을거같네요. 주석을 달아두도록 하겠습니다.

**Comment by starplanter93** [comment]
> 네 zustand사용해볼겸 목데이터로 사용하려고 파일에 넣어두었습니다. 분리되면 다른분들이 혼동이 생길거같아서 넣어두었는데 주석이나, 다른 커맨트가 없어서 혼동이 생겼을거같네요. 주석을 달아두도록 하겠습니다.

확인했습니다~
