### ISSUE TITLE
로그인없이 둘러보기하면 승민님 계정으로 로그인되는것같은데 문제없나요?

### ISSUE THREAD

**Issue by starplanter93** [EthanJcoding/LoReady-Web#60]
로그인없이 둘러보기하면 승민님 계정으로 로그인되는것같은데 문제없나요?

아이디 털리는거 아니에요??

**Comment by seungmin2ee** [comment]
규식님 오랜만이에요🤗 로그인은 데모 계정으로 되는거라 괜찮아요! 아마도 프로필이미지가 같아서 그렇게 보였나봐요ㅋㅋ
